/**:
  ros__parameters:
    global_slope_max_angle_deg: 10.0
    local_slope_max_angle_deg: 25.0 # recommended 30.0 for non elevation_grid_mode
    split_points_distance_tolerance: 0.2
    use_virtual_ground_point: True
    split_height_distance: 0.2
    non_ground_height_threshold: 0.20
    grid_size_m: 0.5
    grid_mode_switch_radius: 150.0
    gnd_grid_buffer_size: 5
    detection_range_z_max: 3.2
    elevation_grid_mode: true
    use_recheck_ground_cluster: true
    recheck_start_distance: 20.0
    use_lowest_point: true
    low_priority_region_x: -20.0
    center_pcl_shift: 0.0
    sector_angle_deg: 1.0
    # debug parameters
    publish_processing_time_detail: false
    max_radius: 240.0
    gnd_cell_buffer_size: 5
    gnd_cell_size: 0.5
    gnd_cell_height: 0.2